#!/usr/bin/env bash
#
# Guard the git hooks git-hooks.nix generates, so a nix store
# garbage-collection degrades them into a message instead of a broken repo.
#
# `pre-commit install` writes a hook from its own template, and nixpkgs patches
# that template to pin absolute store paths — the interpreter in the shebang,
# and the driver in the final `exec`. Upstream's template guards its pinned
# path (`[ -x "$INSTALL_PYTHON" ]`, then `command -v pre-commit`, then an
# error); nixpkgs replaces that whole branch with one bare `exec`. Collect
# either path and `git commit` fails as `fatal: cannot exec
# '.git/hooks/pre-commit': No such file or directory` — a file that plainly
# exists, an error naming neither git hooks nor a way back. The workaround it
# invites is `--no-verify`, which drops every check rather than this one.
#
# So this restores the shape upstream ships, over the path nixpkgs pins. The
# `INSTALL_PYTHON` branch is deliberately not restored: nixpkgs sets it to a
# bare python that cannot import `pre_commit` (checked 2026-08-12), so reaching
# it would trade one opaque failure for another.
#
# Run from dev-shell entry, after the hooks are installed. It is idempotent,
# and re-applies after `pre-commit install` regenerates a hook unguarded.
#
#   scripts/harden-git-hooks.sh [hooks-dir]   # hooks-dir defaults to this repo's
#   scripts/harden-git-hooks.sh --self-test   # red/green pair, also a flake check
#
# The hooks-dir argument exists for the self-test, which needs a hook whose
# pinned paths really are gone rather than one whose paths might be.
set -euo pipefail

MARKER='# --- guarded by scripts/harden-git-hooks.sh (#98) ---'

harden_dir() {
  local hooks_dir=$1 hook pinned tmp

  [ -d "$hooks_dir" ] || return 0

  for hook in "$hooks_dir"/*; do
    [ -f "$hook" ] || continue

    # Only pre-commit's generated hooks, and only once. Anything else here — a
    # sample, a hook someone wrote — is left alone.
    grep -q '^# File generated by pre-commit' "$hook" || continue
    grep -qF "$MARKER" "$hook" && continue

    # The pinned driver, read off the `exec` line the guard replaces. Should
    # the template ever stop matching, that is a silent no-op — which is what
    # the self-test's red case is for.
    pinned="$(sed -n 's|^exec \(/nix/store/[^ ]*\) "${ARGS\[@\]}"$|\1|p' "$hook")"
    [ -n "$pinned" ] || continue

    tmp="$(mktemp)"
    {
      # A portable shebang. The pinned bash is the least legible of the three
      # failures: the kernel refuses the interpreter, so the hook never runs
      # and nothing it could have said gets the chance to be said.
      echo '#!/usr/bin/env bash'
      sed -e '1d' -e '/^exec \/nix\/store\/.* "${ARGS\[@\]}"$/d' "$hook"
      echo "$MARKER"
      sed "s|__PINNED__|$pinned|g" <<'GUARD'
PRE_COMMIT='__PINNED__'

if [ ! -x "$PRE_COMMIT" ]; then
    PRE_COMMIT="$(command -v pre-commit 2>/dev/null || true)"
fi

# The config is a store symlink too, regenerated on dev-shell entry. It holds
# its own gc root, so it outlives the driver — but where it does dangle, every
# hook entry named inside it was collected with it, and a fallback driver would
# only fail later and less clearly.
if [ -L .pre-commit-config.yaml ] && [ ! -e .pre-commit-config.yaml ]; then
    echo '.pre-commit-config.yaml points into the nix store, and the target is gone.' >&2
    echo 'Re-enter the dev shell to regenerate it:  nix develop -c true  (or: direnv reload)' >&2
    exit 1
fi

if [ -z "$PRE_COMMIT" ]; then
    echo 'pre-commit is gone, so this hook cannot run its checks.' >&2
    echo 'The store path it pins was collected, and no pre-commit is on PATH:' >&2
    echo '  __PINNED__' >&2
    echo 'Re-enter the dev shell to rebuild it:  nix develop -c true  (or: direnv reload)' >&2
    echo 'Do not reach for --no-verify: it skips every check, not just this one.' >&2
    exit 1
fi

exec "$PRE_COMMIT" "${ARGS[@]}"
GUARD
    } >"$tmp"

    cat "$tmp" >"$hook"
    rm -f "$tmp"
    chmod +x "$hook"
    echo "guarded $(basename "$hook") against a collected store path" >&2
  done
}

fail() {
  echo "self-test: $1" >&2
  exit 1
}

# A generated hook whose three pinned paths are all gone, hardened, then run in
# each state the guard distinguishes. The green cases go through `bash` rather
# than the shebang: nix's Linux build sandbox has no /usr/bin/env, so executing
# the hardened hook directly would fail there for a reason unrelated to what is
# under test. The shebang is asserted as text instead.
self_test() {
  local dir out status

  dir="$(mktemp -d)"
  # Expanded now, not at exit: `dir` is a local and the trap fires after it is
  # out of scope.
  trap "rm -rf '$dir'" EXIT
  mkdir -p "$dir/hooks" "$dir/stub"

  cat >"$dir/hooks/pre-commit" <<'HOOK'
#!/nix/store/collected0000000000000000000000-bash-5.3p9/bin/bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/nix/store/collected0000000000000000000000-python3/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

exec /nix/store/collected0000000000000000000000-pre-commit-4.5.1/bin/pre-commit "${ARGS[@]}"
HOOK
  chmod +x "$dir/hooks/pre-commit"

  # Red, twice: the generated hook is broken by a collection at the shebang
  # and again at the exec, and says nothing useful about either.
  ! "$dir/hooks/pre-commit" >/dev/null 2>&1 ||
    fail 'the unguarded hook ran with a collected interpreter'
  ! bash "$dir/hooks/pre-commit" >/dev/null 2>&1 ||
    fail 'the unguarded hook ran with a collected driver'

  harden_dir "$dir/hooks" 2>/dev/null

  [ "$(head -1 "$dir/hooks/pre-commit")" = '#!/usr/bin/env bash' ] ||
    fail 'the shebang was not made portable'

  # Green: a collected driver falls back to whatever is on PATH.
  printf '#!%s\necho FELL-BACK\n' "$BASH" >"$dir/stub/pre-commit"
  chmod +x "$dir/stub/pre-commit"
  out="$(cd "$dir" && PATH="$dir/stub:$PATH" bash ./hooks/pre-commit)" ||
    fail 'the guarded hook failed with pre-commit on PATH'
  case "$out" in
    *FELL-BACK*) ;;
    *) fail 'the fallback did not reach pre-commit on PATH' ;;
  esac

  # Green: with nothing to fall back to, it names the cause and the recovery
  # and still refuses the commit.
  status=0
  out="$(cd "$dir" && PATH=/nonexistent "$BASH" ./hooks/pre-commit 2>&1)" || status=$?
  [ "$status" -eq 1 ] || fail "expected exit 1 with no pre-commit, got $status"
  case "$out" in
    *'nix develop'*) ;;
    *) fail 'the failure named no recovery' ;;
  esac

  # Green: a dangling config is reported as itself, not as a missing driver.
  ln -s /nix/store/collected0000000000000000000000-config.json \
    "$dir/.pre-commit-config.yaml"
  status=0
  out="$(cd "$dir" && PATH="$dir/stub:$PATH" bash ./hooks/pre-commit 2>&1)" || status=$?
  [ "$status" -eq 1 ] || fail "expected exit 1 with a dangling config, got $status"
  case "$out" in
    *'.pre-commit-config.yaml'*) ;;
    *) fail 'the dangling config was not named' ;;
  esac

  echo 'self-test: ok'
}

case "${1:-}" in
  --self-test) self_test ;;
  *) harden_dir "${1:-$(git rev-parse --git-path hooks)}" ;;
esac
